name: Bump

on:
  schedule:
    # Every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Test bump
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.TOKEN}}
        run: brew bump-formula-pr --no-audit --no-browse --version=0.138.2 helmfile
      - name: Bump formulae
        if: ${{false}}
        uses: dawidd6/action-homebrew-bump-formula@v3
        continue-on-error: true
        with:
          token: ${{secrets.TOKEN}}
          livecheck: true
        env:
          HOMEBREW_LIVECHECK_WATCHLIST: formulae
          HOMEBREW_STDERR: 1
