name: Bump

on:
  schedule:
    # Every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Bump formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        continue-on-error: true
        with:
          token: ${{secrets.TOKEN}}
          livecheck: true
        env:
          HOMEBREW_LIVECHECK_WATCHLIST: formulae
